"""Initial

Revision ID: f64546bdae1e
Revises: 
Create Date: 2026-08-16 17:31:53.467854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f64546bdae1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
        sa.Column('id', sa.String(length=36), nullable=False), sa.Column('keyword', sa.String(length=255), nullable=False),
        sa.Column('dm_message', sa.Text(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('keyword'))
    op.create_index(op.f('ix_rules_keyword'), 'rules', ['keyword'], unique=False)
    op.create_table('processed_events',
        sa.Column('event_id', sa.String(length=255), nullable=False), sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('comment_id', sa.String(length=255), nullable=False), sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False), sa.Column('post_id', sa.String(length=255), nullable=False),
        sa.Column('comment_text', sa.Text(), nullable=False), sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('processed', sa.Boolean(), nullable=False), sa.Column('duplicates_blocked', sa.Integer(), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('event_id'))
    op.create_table('dm_records',
        sa.Column('id', sa.String(length=36), nullable=False), sa.Column('rule_id', sa.String(length=36), nullable=False),
        sa.Column('recipient_user_id', sa.String(length=255), nullable=False), sa.Column('comment_id', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'SENT', 'FAILED', name='dm_status'), nullable=False),
        sa.Column('attempts', sa.Integer(), server_default='0', nullable=False), sa.Column('dm_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_dm_records_rule_id'), 'dm_records', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dm_records_rule_id'), table_name='dm_records')
    op.drop_table('dm_records')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_rules_keyword'), table_name='rules')
    op.drop_table('rules')
    sa.Enum('QUEUED', 'PROCESSING', 'SENT', 'FAILED', name='dm_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
